/**
 * AuthResponse model - matches backend DTO
 * NOTE: This should ideally be generated by OpenAPI, but creating manually for now
 */
export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
}

