/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HumanOutput } from './humanOutput';


export interface CityOutput { 
    id?: number;
    name?: string;
    humans?: Array<HumanOutput>;
}

