/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HumanOutput { 
    id?: number;
    name?: string;
    x?: number;
    y?: number;
    creativity?: number;
    intellect?: number;
    sociability?: number;
    practicality?: number;
    personality?: HumanOutput.PersonalityEnum;
    scienceSkill?: number;
    cultureSkill?: number;
    socialSkill?: number;
    totalScienceContributed?: number;
    totalCultureContributed?: number;
    totalSocialContributed?: number;
    busy?: boolean;
}
export namespace HumanOutput {
    export const PersonalityEnum = {
        Visionary: 'VISIONARY',
        Engineer: 'ENGINEER',
        Storyteller: 'STORYTELLER',
        Leader: 'LEADER',
        Thinker: 'THINKER',
        Dreamer: 'DREAMER',
        Balanced: 'BALANCED'
    } as const;
    export type PersonalityEnum = typeof PersonalityEnum[keyof typeof PersonalityEnum];
}


