/**
 * Humanaity API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HumanInput { 
    busy?: boolean;
    name?: string;
    x?: number;
    y?: number;
    creativity?: number;
    intellect?: number;
    sociability?: number;
    practicality?: number;
    personality?: HumanInput.PersonalityEnum;
    cityId: number;
}
export namespace HumanInput {
    export const PersonalityEnum = {
        Visionary: 'VISIONARY',
        Engineer: 'ENGINEER',
        Storyteller: 'STORYTELLER',
        Leader: 'LEADER',
        Thinker: 'THINKER',
        Dreamer: 'DREAMER',
        Balanced: 'BALANCED'
    } as const;
    export type PersonalityEnum = typeof PersonalityEnum[keyof typeof PersonalityEnum];
}


